"""Train a compact TFLite classifier on the verified audio features.

The feature-input model is the accurate deployment candidate.  Its input is
the 501-element feature vector generated by ``train_audio_baseline.py`` and
its output is the six class probabilities.  A later Android integration can
port the same NumPy feature recipe, or the feature extractor can be folded
into a raw-waveform model once the DSP layer has been validated on-device.
"""

from __future__ import annotations

import argparse
import csv
import json
import tempfile
from pathlib import Path

import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

from train_audio_baseline import build_split


RANDOM_SEED = 42
BATCH_SIZE = 16


def build_model(feature_count: int, class_count: int, train_features: np.ndarray) -> tf.keras.Model:
    inputs = tf.keras.Input(shape=(feature_count,), name="audio_features")
    normalization = tf.keras.layers.Normalization(axis=-1, name="feature_normalization")
    normalization.adapt(train_features)
    x = normalization(inputs)
    x = tf.keras.layers.Dense(128, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.20)(x)
    x = tf.keras.layers.Dense(64, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.10)(x)
    outputs = tf.keras.layers.Dense(class_count, activation="softmax", name="probabilities")(x)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def evaluate_model(model: tf.keras.Model, features: np.ndarray, labels: np.ndarray, classes: list[str]) -> dict[str, object]:
    probabilities = model.predict(features, batch_size=BATCH_SIZE, verbose=0)
    predicted = np.argmax(probabilities, axis=1)
    return {
        "sample_count": int(labels.size),
        "accuracy": float(accuracy_score(labels, predicted)),
        "macro_f1": float(f1_score(labels, predicted, labels=np.arange(len(classes)), average="macro", zero_division=0)),
        "classification_report": classification_report(
            labels,
            predicted,
            labels=np.arange(len(classes)),
            target_names=classes,
            output_dict=True,
            zero_division=0,
        ),
        "classes": classes,
        "confusion_matrix": confusion_matrix(labels, predicted, labels=np.arange(len(classes))).tolist(),
        "predicted": predicted,
        "probabilities": probabilities,
    }


def export_tflite(model: tf.keras.Model, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # On Windows, TensorFlow may leave restrictive ACLs on a SavedModel created
    # below the project directory.  Use the system temporary directory for the
    # intermediate export and only write the final TFLite artifact here.
    with tempfile.TemporaryDirectory(prefix="knok_tflite_") as temporary_dir:
        # TensorFlow creates this non-existent leaf itself. Passing the already
        # existing TemporaryDirectory root can fail on Windows when it tries
        # to create the SavedModel's ``variables`` subdirectory.
        saved_model_dir = Path(temporary_dir) / "saved_model"
        model.export(saved_model_dir, verbose=False)
        converter = tf.lite.TFLiteConverter.from_saved_model(str(saved_model_dir))
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_types = [tf.float16]
        output_path.write_bytes(converter.convert())


def verify_tflite(model_path: Path, sample: np.ndarray) -> dict[str, object]:
    interpreter = tf.lite.Interpreter(model_path=str(model_path))
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]
    interpreter.set_tensor(input_details["index"], sample[:1].astype(np.float32))
    interpreter.invoke()
    output = interpreter.get_tensor(output_details["index"])
    return {
        "input_shape": input_details["shape"].tolist(),
        "input_dtype": str(input_details["dtype"]),
        "output_shape": output_details["shape"].tolist(),
        "output_dtype": str(output_details["dtype"]),
        "output_sum": float(output[0].sum()),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-dir", type=Path, default=Path("dataset/with_unknown"))
    parser.add_argument("--output-dir", type=Path, default=Path("artifacts/feature_tflite"))
    parser.add_argument("--epochs", type=int, default=100)
    args = parser.parse_args()

    tf.keras.utils.set_random_seed(RANDOM_SEED)
    tf.get_logger().setLevel("ERROR")
    dataset_dir = args.dataset_dir.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    with (dataset_dir / "manifest.csv").open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    classes = sorted({row["label"] for row in rows})
    label_to_index = {label: index for index, label in enumerate(classes)}

    train_x, train_labels_text, _ = build_split(rows, dataset_dir, "train")
    validation_x, validation_labels_text, _ = build_split(rows, dataset_dir, "validation")
    test_x, test_labels_text, test_files = build_split(rows, dataset_dir, "test")
    train_y = np.asarray([label_to_index[label] for label in train_labels_text], dtype=np.int32)
    validation_y = np.asarray([label_to_index[label] for label in validation_labels_text], dtype=np.int32)
    test_y = np.asarray([label_to_index[label] for label in test_labels_text], dtype=np.int32)

    model = build_model(train_x.shape[1], len(classes), train_x)
    history = model.fit(
        train_x,
        train_y,
        validation_data=(validation_x, validation_y),
        epochs=args.epochs,
        batch_size=BATCH_SIZE,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(
                monitor="val_accuracy",
                patience=15,
                mode="max",
                restore_best_weights=True,
            )
        ],
        verbose=2,
    )

    validation_result = evaluate_model(model, validation_x, validation_y, classes)
    test_result = evaluate_model(model, test_x, test_y, classes)
    model_path = output_dir / "noise_features_classifier.tflite"
    export_tflite(model, model_path)
    tflite_check = verify_tflite(model_path, test_x)

    (output_dir / "labels.txt").write_text("\n".join(classes) + "\n", encoding="utf-8")
    metrics = {
        "model": "Normalization + Dense(128) + Dense(64) feature classifier",
        "feature_count": int(train_x.shape[1]),
        "feature_source": "tools/train_audio_baseline.py",
        "classes": classes,
        "train_samples": int(train_y.size),
        "validation": {key: value for key, value in validation_result.items() if key not in {"predicted", "probabilities"}},
        "test": {key: value for key, value in test_result.items() if key not in {"predicted", "probabilities"}},
        "tflite": tflite_check,
        "epochs_ran": len(history.history.get("loss", [])),
    }
    with (output_dir / "metrics.json").open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, ensure_ascii=False, indent=2)

    with (output_dir / "test_predictions.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["processed_file", "actual_label", "predicted_label", "confidence"])
        writer.writeheader()
        for file_name, actual_index, predicted_index, probabilities in zip(
            test_files, test_y, test_result["predicted"], test_result["probabilities"]
        ):
            writer.writerow(
                {
                    "processed_file": file_name,
                    "actual_label": classes[int(actual_index)],
                    "predicted_label": classes[int(predicted_index)],
                    "confidence": f"{float(np.max(probabilities)):.6f}",
                }
            )

    print(f"Train samples: {train_y.size}")
    print(f"Validation accuracy: {validation_result['accuracy']:.4f}")
    print(f"Validation macro F1: {validation_result['macro_f1']:.4f}")
    print(f"Test samples: {test_y.size}")
    print(f"Test accuracy: {test_result['accuracy']:.4f}")
    print(f"Test macro F1: {test_result['macro_f1']:.4f}")
    print(f"TFLite: {model_path}")
    print(f"TFLite check: {tflite_check}")


if __name__ == "__main__":
    main()
